# Generated by Django 4.1.3 on 2022-12-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('nationalId', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=1000)),
                ('birth_date', models.DateField(default=None)),
                ('email', models.CharField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('W', 'Work'), ('NW', 'Not Work')], default='NW', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(max_length=20)),
                ('release_date', models.DateField(default=None)),
                ('expiration_date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_plate', models.CharField(default='', max_length=200)),
                ('vehicle_status', models.CharField(choices=[('W', 'Work'), ('NW', 'Not Work')], default='NW', max_length=2)),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], default='P', max_length=1)),
                ('insurance_status', models.CharField(choices=[('U', 'Updated'), ('NU', 'Not Updated')], default='NU', max_length=2)),
                ('inspection_status', models.CharField(choices=[('U', 'Updated'), ('NU', 'Not Updated')], default='NU', max_length=2)),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vms_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vms_app.driver')),
                ('end', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='vms_app.address')),
                ('start', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='vms_app.address')),
                ('vehicle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driverLicense',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vms_app.driverlicense'),
        ),
    ]
