# Generated by Django 4.1.3 on 2022-12-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driverLicense',
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='driver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='vms_app.driver'),
        ),
    ]
