# Generated by Django 4.1.3 on 2022-12-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_remove_driver_driverlicense_driverlicense_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='driver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='vms_app.driver'),
        ),
    ]
