# Generated by Django 4.1.3 on 2022-12-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_alter_driverlicense_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default='', max_length=200),
        ),
    ]
