# Generated by Django 4.1.3 on 2022-12-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_alter_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='nationalId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phoneNumber',
            field=models.CharField(max_length=100),
        ),
    ]
