# Generated by Django 4.1.3 on 2022-12-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0007_address_state_alter_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nationalId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
