# Generated by Django 4.1.3 on 2022-12-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0008_path_date_alter_driver_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_plate',
            field=models.CharField(default=None, max_length=200, null=True, unique=True),
        ),
    ]
