# Generated by Django 4.1.3 on 2022-12-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0009_alter_vehicle_registration_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='serial_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vms_app.driver'),
        ),
        migrations.AlterField(
            model_name='path',
            name='end',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='end', to='vms_app.address'),
        ),
        migrations.AlterField(
            model_name='path',
            name='start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='start', to='vms_app.address'),
        ),
        migrations.AlterField(
            model_name='path',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vms_app.vehicle'),
        ),
    ]
